package.json
yarn.lock

Updated Typescript generates `exports.__esModules=true` necessary for new SystemJS@ 0.20.x
http://guybedford.com/systemjs-alignment

Updating typescript version ( to have cjs exports __esModule = true )

---

src/mapped-types.spec.ts
src/mapped-types.ts

`DeepReadonly` as implemented right now has a side effect.  All optional keys are converted to required keys.  I think I found a small tweak to the implementation that allows us to preserve the optional key modifier!
I have added a couple test assertions that hopefully help clarify the issue I'm identifying.

Deepreadonly should preserve optional keys

---

README.md
src/index.ts
src/mapped-types.spec.ts
src/mapped-types.ts

`DeepRequired` is to `Required` as `DeepReadonly` is to `Readonly`.
```ts
type NestedProps = {
first?: {
second?: {
name?: string;
};
};
};
let a = {} as NestedProps;
const s1: string = a.first!.second!.name!;
let b = {} as DeepRequired<NestedProps>;
const s2: string = b.first.second.name;
```
<del>It is useful e.g. combining with `idx`:</del>
```ts
const s3: string | null | undefined = idx(b, _ => _.first.second.name); // idx will catch the error of reading from undefined or null
```

Add DeepRequired

---

README.md
src/index.ts
src/mapped-types.spec.ts
src/mapped-types.ts

As I mentioned in the PR https://github.com/piotrwitek/utility-types/pull/33 I have created a new type `DeepNonNullable`.
```ts
type NestedProps = {
first?: null | {
second?: null | {
name?: null | string;
};
};
};
let a = {} as NestedProps;
const s1: string = a.first!.second!.name!;
let b = {} as DeepNonNullable<NestedProps>;
const s2: string = b.first.second.name;
```

Add DeepNonNullable

---

README.md
src/__snapshots__/mapped-types.spec.ts.snap
src/index.ts
src/mapped-types.spec.snap.ts
src/mapped-types.spec.ts
src/mapped-types.ts

This PR adds `PickByValue` and `OmitByValue` per #50.
I also updated tests and README.md.
@piotrwitek I didn't use Jest and snapshots before. Could you please review tests are OK.

add `PickByValue` and `OmitByValue` types.

---

README.md
src/__snapshots__/utility-types.spec.ts.snap
src/index.ts
src/utility-types.spec.snap.ts
src/utility-types.spec.ts
src/utility-types.ts

Added Class utility

---

README.md
src/__snapshots__/mapped-types.spec.ts.snap
src/index.ts
src/mapped-types.spec.snap.ts
src/mapped-types.spec.ts
src/mapped-types.ts

Fixes #52 
We can inline "DeepArray"s later in all deep types once it's figured out.

feat: added DeepPartial<T> mapped type

---

README.md
src/__snapshots__/mapped-types.spec.ts.snap
src/index.ts
src/mapped-types.spec.snap.ts
src/mapped-types.spec.ts
src/mapped-types.ts

feat: added WritableKeys/ReadonlyKeys mapped types

---

src/mapped-types.ts
src/utility-types.ts

#34 - added usage document in JSDoc

---

README.md
src/__snapshots__/utility-types.spec.ts.snap
src/utility-types.spec.snap.ts
src/utility-types.spec.ts
src/utility-types.ts

Add mixed type
- Resolved #72 

Add mixed type

---

README.md
src/__snapshots__/mapped-types.spec.ts.snap
src/index.ts
src/mapped-types.spec.snap.ts
src/mapped-types.spec.ts
src/mapped-types.ts

- Resolved #XXX
For bugfixes:
I add `PartOptional `

feat: add PartOptional

---

README.md

Fixes docs to include `Omit` as built-in type.
- Resolved #83

added built-in next to Omit 

---

src/__snapshots__/mapped-types.spec.ts.snap
src/mapped-types.spec.snap.ts
src/mapped-types.spec.ts
src/mapped-types.ts

#41  Description
FunctionKeys and NonFunctionKeys cant work with optional keys
[example](https://typescript-play.js.org/#code/C4TwDgpgBAYgrgOwMbAJYHsEGkIgM4A8AKlBAB7AQIAmeU6ARgFYQoB8UAvFAN4BQUKAG0sUVAigBrXOgBmUIgF0AXApGLSFKrViIUGCQH4oo1QggA3CACc+AXyHSQchYr59yYdNeBRQkKAA5THhkNEwcfGJNSho6RhZ2Ll4BYVFxKRl5JVUidRjtOlD9TChjcytrKFUse0cs1wBud39oAFlUMghqAAVrdDA6bn5BBABDAFsIVTxga3EAc2bBPAhgQMnpqAAKcamZucWASi4OC3RUamWoPHQpyLxDA-mEJdTbqZgEJ52AOn+xtYFnhVGMECATpwOGCQM07M0+K0TLghrowgYHgQOl1ev1BmxEeBoOYAO6RZLBBDFcLYFFYzrdPoDPBsIA)
```ts
type FunctionKeys<T extends object> = {
[K in keyof T]: T[K] extends Function ? K : never
}[keyof T]
export type NonFunctionKeys<T extends object> = {
[K in keyof T]: T[K] extends Function ? never : K
}[keyof T];
type MixedProps = {
name: string;
setName: (name: string) …
```

fix: FunctionKey and NonFunctionKeys

---

README.md
src/mapped-types.ts

`T` is a subtype of `T1`, not vice versa. `T` has all of the same properties as `T1` and possibly more. `T1` has a subset of the properties of `T`.

Fix typo in README

---

README.md
src/mapped-types.ts

I also noticed that `Exact` doesn't seem to be in the README.md (because I was going to add this same line to Exact's description).  Is this intended?

adds SEO content for Brand

---

README.md
src/__snapshots__/mapped-types.spec.ts.snap
src/index.ts
src/mapped-types.spec.snap.ts
src/mapped-types.spec.ts
src/mapped-types.ts

Adds a new type Required<T, K> that makes keys K in type T required (default keyof T). Compatible with the built-in Required type.
Credit to @vhenzl for the basic implementation.
- Resolved #93

Add new Required<T, K> as the opposite of Optional<T, K>

---

README.md

The URL hash for Required changed when a type parameter was added breaking the link in the TOC. While I was there I noticed a typo in the in the Optional example and fixed it.

Fix link and typo in README

---

README.md

There is Flow typing syntax In TypeScript example of `ValuesType`
- Resolved #104
For bugfixes:

Fix typo in ValuesType with flow syntax

---

src/__snapshots__/mapped-types.spec.ts.snap
src/__snapshots__/utility-types.spec.ts.snap
src/mapped-types.spec.snap.ts
src/mapped-types.spec.ts
src/mapped-types.ts
src/utility-types.spec.snap.ts

fixes #106
This isn't as clean as I'd like—ideally a recursive application would have no impact. For example, the newly added test would match as if it weren't applied twice:
```
exports[`DeepReadonly testType<DeepReadonly<DeepReadonly<NestedArrayProps>>['first']['second']>() 1`] = `"_DeepReadonlyArray<_DeepReadonlyObject<{ name: string; }>>"`;
```
Above, the `_DeepReadonlyObject` is superfluous and isn't there if applied only once.
```
exports[`DeepReadonly testType<DeepReadonly<NestedArrayProps>['first']['second']>() 1`] = `"_DeepReadonlyArray<{ name: string; }>"`;
```
- Resolved #106
For bugfixes:

Make applying DeepReadonly idempotent

---

README.md
src/__snapshots__/mapped-types.spec.ts.snap
src/index.ts
src/mapped-types.spec.snap.ts
src/mapped-types.spec.ts
src/mapped-types.ts

Add `UnionToIntersection` type.
- Resolved #49
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#49: Support UnionToIntersection](https://issuehunt.io/repos/76400842/issues/49)
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

[Feature] Add `UnionToIntersection` type

---

README.md
src/__snapshots__/mapped-types.spec.ts.snap
src/index.ts
src/mapped-types.spec.snap.ts
src/mapped-types.spec.ts
src/mapped-types.ts

Add `Mutable` type.
- Resolved #27
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#27: Include Mutable type](https://issuehunt.io/repos/76400842/issues/27)
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

Add `Mutable` type

---

README.md
src/__snapshots__/mapped-types.spec.ts.snap
src/aliases-and-guards.ts
src/mapped-types.spec.snap.ts
src/mapped-types.spec.ts

Added `null | undefined` to `Primitive` and `isPrimitive`
- Resolved #113 
For bugfixes:

Added `null | undefined` to `Primitive` and `isPrimitive`

---

src/__snapshots__/mapped-types.spec.ts.snap
src/mapped-types.spec.snap.ts
src/mapped-types.spec.ts
src/mapped-types.ts

- Resolved #123 
For bugfixes:

Remove `undefined` from `keyof` result of (Pick|Omit)ByValue(Exact)?

---

README.md
src/__snapshots__/aliases-and-guards.spec.ts.snap
src/aliases-and-guards.spec.snap.ts
src/aliases-and-guards.spec.ts
src/aliases-and-guards.ts
src/index.ts

Introduced in TS 3.7 with nullish coalescing operator (see [here][1])
[1]: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#nullish-coalescing

add "Nullish" type alias

---

README.md

Fixed a typo in the documentation for how to use `$Call`
- Resolved #XXX
See https://github.com/piotrwitek/utility-types/issues/149 . I don't know if this patch should close that issue, though.
For bugfixes:

Fix typo in $Call documentation

---

README.md

This adds a link to `ReturnType` from the `$Call` docs so that the user can decide if that will be easier for them. I personally had run into issues with union types where `ReturnType` worked better.
I wasn't sure if it would be better to link to the `ReturnType` implementation in `utility-types` or not, just let me know.
- Resolved #XXX
See https://github.com/piotrwitek/utility-types/issues/149
For bugfixes:

Link to ReturnType from $Call docs

---

README.md
src/utility-types.ts

Fixed a typo in the usage example of `$ReadOnly<T>`.
- Resolved #XXX
Refer to #156 .
For bugfixes:

fix: ReadOnly<T> has a typo in its documentation (#156)

---

src/__snapshots__/mapped-types.spec.ts.snap
src/mapped-types.spec.snap.ts
src/mapped-types.spec.ts
src/mapped-types.ts

DeepPartial supports the assignment of `{}` when the passed type is generic:
```ts
const result: DeepPartial<T> = {}
```
It's not possible to test with `dts-jest`, so I setup an additional `tsconfig.test-d.json` used to run `tsc` on `src/**/*.test-d.ts` files.
It would be even better to integrate types testing library like [tsd](https://github.com/SamVerschueren/tsd), to be able to assert also cases when type error is expected.
- Resolved #183
For bugfixes:

fix: DeepPartial with generic parameter should allow assigning {}

---

README.md
src/__snapshots__/mapped-types.spec.ts.snap
src/index.ts
src/mapped-types.spec.snap.ts
src/mapped-types.spec.ts
src/mapped-types.ts

Added UnionKeys type as discussed on the issue linked below
- Resolved [Allow for a AllUnionKeys](https://github.com/piotrwitek/utility-types/issues/192)
For bugfixes:

Added "UnionKeys" type
